In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3,4,5]])
print(a)
print(a.shape)

[[1 2 3 4 5]]
(1, 5)


In [3]:
a.ndim # to know dimensions of an array

2

In [4]:
b = np.array([[1,2, 3], [3,4, 5]])
print(b)
print(b.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


In [5]:
b.ndim

2

### Array Creation by given range

In [6]:
arr = np.arange(2, 11, 2)
arr

array([ 2,  4,  6,  8, 10])

In [7]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# change the shape :

arr2 = np.arange(1, 11)
print(arr2.shape)
arr3 = arr2.reshape(5, 2, 1)
arr3

(10,)


array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [9]:
arr2.reshape(5, 1, 2)

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

In [10]:
arr4 = np.arange(1, 17)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
print(arr4.reshape(4, 2, 2))
print(arr4.reshape(4, 2, 2).shape)
print(arr4.reshape(4, 2, 2).ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3
