#### 1. Create a 2D NumPy array containing numbers 1 to 5 in a single row. Print the array, its shape, and ndim.


In [4]:
# 1. Create a 2D NumPy array containing numbers 1 to 5 in a single row. Print the array, its shape, and ndim.

import numpy as np

a = np.array([[1, 2, 3, 4, 5]])

print(a)  # prints array
print(a.shape)  # array shape
print(a.ndim)  # array dimensions

[[1 2 3 4 5]]
(1, 5)
2


#### 2. Create a 2D NumPy array with 3 rows and 2 columns. Print its shape and number of dimensions.


In [5]:
# 2. Create a 2D NumPy array with 3 rows and 2 columns. Print its shape and number of dimensions.

import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])  # 3 rows and 2 columns

print(array_2d)  # prints array
print(array_2d.shape)  # array shape
print(array_2d.ndim)  # array dimensions

[[1 2 3]
 [4 5 6]]
(2, 3)
2


#### 3. Create a 3D NumPy array of shape (2, 2, 2) and print its ndim and shape.


In [6]:
# 3. Create a 3D NumPy array of shape (2, 2, 2) and print its ndim and shape.

import numpy as np

array_3d = np.array([[[2, 2], [2, 2]], [[2, 2], [2, 2]]])  # 3d array
array_3d = np.arange(1, 9).reshape(2, 2, 2)  # reshaping the array to (2, 2, 2)

print(array_3d)
print(array_3d.ndim)
print(array_3d.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


### 4. Take 5 numbers from the user and create a NumPy array. Display the shape and ndim.


In [7]:
# 4. Take 5 numbers from the user and create a NumPy array. Display the shape and ndim.

import numpy as np

user_list = []

for i in range(5):

    num = float(input(f"Number {i+1} :"))
    user_list.append(num)

arr = np.array(user_list)
print("NumPy Array : ", arr)
print("Number of dimensions :", arr.ndim)
print("Shape :", arr.shape)

NumPy Array :  [1. 2. 3. 4. 5.]
Number of dimensions : 1
Shape : (5,)


#### 5. Create an array using np.arange() containing all even numbers from 2 to 20.


In [8]:
# 5. Create an array using np.arange() containing all even numbers from 2 to 20.

import numpy as np

even_array = np.arange(2, 21, 2)  # start point, end point, skip numbers

print("Even Array :", even_array)

Even Array : [ 2  4  6  8 10 12 14 16 18 20]


#### 6. Create an array using np.arange() containing all odd numbers from 1 to 25.


In [9]:
# 6. Create an array using np.arange() containing all odd numbers from 1 to 25.

import numpy as np

odd_array = np.arange(1, 26, 2)  # start point, end point always +1, skip numbers

print("Odd Array :", odd_array)

Odd Array : [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


#### 7. Generate numbers from 50 to 100 with a step size of 5 using np.arange().


In [10]:
# 7. Generate numbers from 50 to 100 with a step size of 5 using np.arange().

import numpy as np

array = np.arange(5, 101, 5)  # start point, end point always +1, skip numbers

print("5 steps sized Array :", array)

5 steps sized Array : [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


#### 8. Create an array from 1 to 12 and reshape it into (3, 4).


In [11]:
# 8. Create an array from 1 to 12 and reshape it into (3, 4).

import numpy as np

original_array = np.arange(1, 13)

reshaped_array = original_array.reshape(3, 4)

print (original_array)
print (reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 9. Create an array from 1 to 24 and reshape it into (2, 3, 4).


In [12]:
# 9. Create an array from 1 to 24 and reshape it into (2, 3, 4).

import numpy as np

original_array = np.arange(1, 25)

reshaped_array = original_array.reshape(2, 3, 4)

print (original_array)
print (reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


#### 10. Create an array from 1 to 27 and reshape it into a 3D array of shape (3, 3, 3).


In [13]:
# 10. Create an array from 1 to 27 and reshape it into a 3D array of shape (3, 3, 3).

import numpy as np

original_array = np.arange(1, 28)

reshaped_array = original_array.reshape(3, 3, 3)

print (original_array)
print (reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


#### 11. Take the number of rows and columns from the user. Create an array using np.arange() and reshape it according to the user's input.


In [14]:
# 11. Take the number of rows and columns from the user. Create an array using np.arange() and reshape it according to the user's input.

import numpy as np

rows = int(input("Enter the number of rows : "))
cols = int(input("Enter the number of columns : "))

total_elements = rows * cols

original_array = np.arange(1, total_elements + 1)
reshaped_matrix = original_array.reshape(rows, cols)

print(f"\nGenerated 1D array of {total_elements} elements:")
print(original_array)

print(f"\nReshaped 2D Matrix ({rows}x{cols}):")
print(reshaped_matrix)


Generated 1D array of 2 elements:
[1 2]

Reshaped 2D Matrix (1x2):
[[1 2]]


#### 12. Take rows and columns from the user. If reshape is not possible, display a custom error message instead of crashing.


In [15]:
# 12. Take rows and columns from the user. If reshape is not possible, display a custom error message instead of crashing.

import numpy as np

rows = int(input("Enter the number of rows : "))
cols = int(input("Enter the number of columns : "))

total_elements = rows * cols

try:
    original_array = np.arange(1, total_elements + 1)
    reshaped_matrix = original_array.reshape(rows, cols)

    print(f"\nGenerated 1D array of {total_elements} elements:")
    print(original_array)

    print(f"\nReshaped 2D Matrix ({rows}x{cols}):")
    print(reshaped_matrix)

except ValueError:
    print(f"\nError: Cannot reshape array of size {total_elements} into shape ({rows}, {cols}). Please check your input.")


Generated 1D array of 4 elements:
[1 2 3 4]

Reshaped 2D Matrix (2x2):
[[1 2]
 [3 4]]


#### 13. Take dimensions x, y, and z from the user and reshape an array accordingly. Handle invalid dimensions using try-except.


In [16]:
# 13. Take dimensions x, y, and z from the user and reshape an array accordingly. Handle invalid dimensions using try-except.

import numpy as np

x = int(input("Enter dimension x : "))
y = int(input("Enter dimension y : "))
z = int(input("Enter dimension z : "))

total_elements = x * y * z

try:
    original_array = np.arange(1, total_elements + 1)
    reshaped_array = original_array.reshape(x, y, z)

    print(f"\nGenerated 1D array of {total_elements} elements:")
    print(original_array)

    print(f"\nReshaped 3D Array ({x}x{y}x{z}):")
    print(reshaped_array)

except ValueError:
    print(f"\nError: Cannot reshape array of size {total_elements} into shape ({x}, {y}, {z}). Please check your input.")


Generated 1D array of 20 elements:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Reshaped 3D Array (5x2x2):
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


#### 14. Create an array from 1 to 30. Reshape it into all possible valid 2D shapes and print them.


In [17]:
# 14. Create an array from 1 to 30. Reshape it into all possible valid 2D shapes and print them.

import numpy as np

original_array = np.arange(1, 31)

total_elements = original_array.size

print(f"Original Array: {original_array}\n")
print("All possible valid 2D shapes and their corresponding reshaped arrays:")

for i in range(1, total_elements + 1):
    if total_elements % i == 0:  # Check if i is a factor of total_elements
        rows = i
        cols = total_elements // i
        reshaped_array = original_array.reshape(rows, cols)
        print(f"Shape ({rows}, {cols}):\n{reshaped_array}\n")

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]

All possible valid 2D shapes and their corresponding reshaped arrays:
Shape (1, 30):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
  25 26 27 28 29 30]]

Shape (2, 15):
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]]

Shape (3, 10):
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

Shape (5, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Shape (6, 5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Shape (10, 3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]]

Shape (15, 2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 

#### 15. Create an array from 1 to 16. Convert it into shape (4, 2, 2). Print shape and ndim.


In [18]:
# 15. Create an array from 1 to 16. Convert it into shape (4, 2, 2). Print shape and ndim.

import numpy as np

original_array = np.arange(1, 17)
reshaped_array = original_array.reshape(4, 2, 2)

print(f"Original Array: {original_array}\n")
print(f"Reshaped Array (4, 2, 2):\n{reshaped_array}\n")
print(f"Shape: {reshaped_array.shape}")
print(f"Number of dimensions (ndim): {reshaped_array.ndim}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]

Reshaped Array (4, 2, 2):
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]

Shape: (4, 2, 2)
Number of dimensions (ndim): 3


#### 16. Create an array from 1 to 64. Convert it into shape (4, 4, 4) and print all details.


In [19]:
# 16. Create an array from 1 to 64. Convert it into shape (4, 4, 4) and print all details.

import numpy as np

original_array = np.arange(1, 65)
reshaped_array = original_array.reshape(4, 4, 4)

print(f"Original Array: {original_array}\n")
print(f"Reshaped Array (4, 4, 4):\n{reshaped_array}\n")
print(f"Shape: {reshaped_array.shape}")
print(f"Number of dimensions (ndim): {reshaped_array.ndim}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]

Reshaped Array (4, 4, 4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]

Shape: (4, 4, 4)
Number of dimensions (ndim): 3


#### 17. Take n from the user and create an array from 1 to n using np.arange().


In [20]:
# 17. Take n from the user and create an array from 1 to n using np.arange().

import numpy as np

n = int(input("Enter a number n : "))

array = np.arange(1, n + 1)

print("Generated Array from 1 to n :", array)

Generated Array from 1 to n : [1 2]


#### 18. Take start, stop, and step values from the user and create an array using np.arange().


In [21]:
# 18. Take start, stop, and step values from the user and create an array using np.arange().

import numpy as np

start = int(input("Enter the start value : "))
stop = int(input("Enter the stop value : "))
step = int(input("Enter the step value : "))

array = np.arange(start, stop, step)

print("Generated Array with given start, stop, and step values :", array)

Generated Array with given start, stop, and step values : []


#### 19. Write a program that checks whether a given reshape size is valid before calling reshape().


In [22]:
# 19. Write a program that checks whether a given reshape size is valid before calling reshape().

import numpy as np

total_elements = int(input("Enter the total number of elements in the array : "))
rows = int(input("Enter the number of rows for reshape : "))
cols = int(input("Enter the number of columns for reshape : "))

try:
    original_array = np.arange(1, total_elements + 1)
    reshaped_array = original_array.reshape(rows, cols)

    print(f"\nGenerated 1D array of {total_elements} elements:")
    print(original_array)

    print(f"\nReshaped 2D Array ({rows}x{cols}):")
    print(reshaped_array)

except ValueError:
    print(f"\nError: Cannot reshape array of size {total_elements} into shape ({rows}, {cols}). Please check your input.")


Error: Cannot reshape array of size 2 into shape (5, 1). Please check your input.


#### 20. Create an array from 1 to 20 and reshape it into (5, 4). Print only the second row.


In [23]:
# 20. Create an array from 1 to 20 and reshape it into (5, 4). Print only the second row.

import numpy as np

original_array = np.arange(1, 21)
reshaped_array = original_array.reshape(5, 4)

print("Reshaped Array (5, 4):\n", reshaped_array)
print("\nSecond Row of the Reshaped Array:", reshaped_array[1])

Reshaped Array (5, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

Second Row of the Reshaped Array: [5 6 7 8]


#### 21. Create a 3D array of shape (2, 3, 2) and print only the first block.


In [24]:
# 21. Create a 3D array of shape (2, 3, 2) and print only the first block.

import numpy as np

original_array = np.arange(1, 13)
reshaped_array = original_array.reshape(2, 3, 2)

print("Reshaped 3D Array (2, 3, 2):\n", reshaped_array)
print("\nFirst Block of the Reshaped 3D Array:\n", reshaped_array[0])

Reshaped 3D Array (2, 3, 2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

First Block of the Reshaped 3D Array:
 [[1 2]
 [3 4]
 [5 6]]


#### 22. Create an array from 1 to 18 and reshape it into (3, 3, 2). Print its shape, ndim, and total number of elements.


In [25]:
# 22. Create an array from 1 to 18 and reshape it into (3, 3, 2). Print its shape, ndim, and total number of elements.

import numpy as np

original_array = np.arange(1, 19)
reshaped_array = original_array.reshape(3, 3, 2)

print("Reshaped 3D Array (3, 3, 2):\n", reshaped_array)
print("\nShape of the Reshaped Array:", reshaped_array.shape)
print("Number of dimensions (ndim):", reshaped_array.ndim)
print("Total number of elements:", reshaped_array.size)

Reshaped 3D Array (3, 3, 2):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

Shape of the Reshaped Array: (3, 3, 2)
Number of dimensions (ndim): 3
Total number of elements: 18


#### 23. Take an array size from the user. Create an array using np.arange() and display its shape before and after reshaping.


In [26]:
# 23. Take an array size from the user. Create an array using np.arange() and display its shape before and after reshaping.

import numpy as np

array_size = int(input("Enter the size of the array : "))
original_array = np.arange(1, array_size + 1)

print(f"\nOriginal Array: {original_array}")
print(f"Shape of Original Array: {original_array.shape}")

# Reshape the array into a 2D array with appropriate dimensions

try:
    rows = int(input("Enter the number of rows for reshape : "))
    cols = int(input("Enter the number of columns for reshape : "))
    reshaped_array = original_array.reshape(rows, cols)

    print(f"\nReshaped Array ({rows}x{cols}):\n{reshaped_array}")
    print(f"Shape of Reshaped Array: {reshaped_array.shape}")

except ValueError:
    print(f"\nError: Cannot reshape array of size {array_size} into shape ({rows}, {cols}). Please check your input.")


Original Array: [1 2]
Shape of Original Array: (2,)

Error: Cannot reshape array of size 2 into shape (1, 1). Please check your input.


#### 24. Write a program that repeatedly asks the user for reshape dimensions until a valid reshape is entered.


In [ ]:
# 24. Write a program that repeatedly asks the user for reshape dimensions until a valid reshape is entered.

import numpy as np

total_elements = int(input("Enter the total number of elements in the array : "))
original_array = np.arange(1, total_elements + 1)

while True:
    try:
        rows = int(input("Enter the number of rows for reshape : "))
        cols = int(input("Enter the number of columns for reshape : "))
        reshaped_array = original_array.reshape(rows, cols)

        print(f"\nReshaped Array ({rows}x{cols}):\n{reshaped_array}")
        print(f"Shape of Reshaped Array: {reshaped_array.shape}")
        
        break  # Exit the loop if reshape is successful

    except ValueError:
        print(f"\nError: Cannot reshape array of size {total_elements} into shape ({rows}, {cols}). Please check your input and try again.")


Error: Cannot reshape array of size 2 into shape (2, 2). Please check your input and try again.

Error: Cannot reshape array of size 2 into shape (1, 5). Please check your input and try again.

Error: Cannot reshape array of size 2 into shape (6, 2). Please check your input and try again.

Reshaped Array (1x2):
[[1 2]]
Shape of Reshaped Array: (1, 2)


#### 25. Create an array from 1 to 100. Reshape it into (10, 10) and print only the diagonal elements.


In [28]:
# 25. Create an array from 1 to 100. Reshape it into (10, 10) and print only the diagonal elements.

import numpy as np

original_array = np.arange(1, 101)
reshaped_array = original_array.reshape(10, 10)

print("Reshaped Array (10, 10):\n", reshaped_array)
print("\nDiagonal Elements of the Reshaped Array:", np.diag(reshaped_array))

Reshaped Array (10, 10):
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Diagonal Elements of the Reshaped Array: [  1  12  23  34  45  56  67  78  89 100]


#### 26. Create an array from 1 to 36. Reshape it into (3, 3, 4). Print the shape and ndim after reshaping.


In [29]:
# 26. Create an array from 1 to 36. Reshape it into (3, 3, 4). Print the shape and ndim after reshaping.

import numpy as np

original_array = np.arange(1, 37)
reshaped_array = original_array.reshape(3, 3, 4)

print("Reshaped Array (3, 3, 4):\n", reshaped_array)
print("\nShape of the Reshaped Array:", reshaped_array.shape)
print("Number of dimensions (ndim):", reshaped_array.ndim)

Reshaped Array (3, 3, 4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]

Shape of the Reshaped Array: (3, 3, 4)
Number of dimensions (ndim): 3


#### 27. Create a menu-driven program:

#### 1. Show Shape

#### 2. Show Dimensions

#### 3. Reshape Array

#### 4. Exit


In [ ]:
# 27. Create a menu-driven program:
# 1. Show Shape
# 2. Show Dimensions
# 3. Reshape Array
# 4. Exit

import numpy as np

def show_shape(array):
    print(f"Shape of the array: {array.shape}")

def show_dimensions(array):
    print(f"Number of dimensions (ndim): {array.ndim}")

def reshape_array(array):

    try:
        rows = int(input("Enter the number of rows for reshape : "))
        cols = int(input("Enter the number of columns for reshape : "))
        reshaped_array = array.reshape(rows, cols)

        print(f"\nReshaped Array ({rows}x{cols}):\n{reshaped_array}")

    except ValueError:
        print(f"\nError: Cannot reshape array of size {array.size} into shape ({rows}, {cols}). Please check your input and try again.")

def main():

    original_array = np.arange(1, 17)  # Example array from 1 to 16

    while True:
        print("\nMenu:")
        print("1. Show Shape")
        print("2. Show Dimensions")
        print("3. Reshape Array")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == '1':
            show_shape(original_array)
        elif choice == '2':
            show_dimensions(original_array)
        elif choice == '3':
            reshape_array(original_array)
        elif choice == '4':
            print("Exiting the program.")
            
            break
        else:
            print("Invalid choice. Please enter a number between 1 and 4.")

if __name__ == "__main__":
    main()


Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Invalid choice. Please enter a number between 1 and 4.

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Shape of the array: (16,)

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit

Error: Cannot reshape array of size 16 into shape (4, 2). Please check your input and try again.

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Shape of the array: (16,)

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Shape of the array: (16,)

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Shape of the array: (16,)

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Number of dimensions (ndim): 1

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Invalid choice. Please enter a number between 1 and 4.

Menu:
1. Show Shape
2. Show Dimensions
3. Reshape Array
4. Exit
Number of dimensions (ndim): 1

Menu:
1. Show Shape
2. Show Dimensions
3

#### 28. Take dimensions from the user and calculate whether:

#### rows × columns = total elements

#### If yes, reshape the array; otherwise display an error.


In [ ]:
# 28. Take dimensions from the user and calculate whether:
# rows × columns = total elements
# If yes, reshape the array; otherwise display an error.

import numpy as np

total_elements = int(input("Enter the total number of elements in the array : "))
original_array = np.arange(1, total_elements + 1)

rows = int(input("Enter the number of rows for reshape : "))
cols = int(input("Enter the number of columns for reshape : "))

if rows * cols == total_elements:
    reshaped_array = original_array.reshape(rows, cols)

    print(f"\nReshaped Array ({rows}x{cols}):\n{reshaped_array}")

else:
    print(f"\nError: Cannot reshape array of size {total_elements} into shape ({rows}, {cols}). Please check your input.")

#### 29. Create an array from 1 to 48. Let the user choose whether to reshape it into:

#### a) (6, 8)

#### b) (4, 4, 3)

#### c) (2, 2, 2, 6)


In [ ]:
# 29. Create an array from 1 to 48. Let the user choose whether to reshape it into:
# a) (6, 8)
# b) (4, 4, 3)
# c) (2, 2, 2, 6)

import numpy as np

original_array = np.arange(1, 49)

print("Choose a reshape option:")
print("a) (6, 8)")
print("b) (4, 4, 3)")
print("c) (2, 2, 2, 6)")

choice = input("Enter your choice (a, b, or c): ")

if choice == 'a':
    reshaped_array = original_array.reshape(6, 8)

    print(f"\nReshaped Array (6, 8):\n{reshaped_array}")

elif choice == 'b':
    reshaped_array = original_array.reshape(4, 4, 3)

    print(f"\nReshaped Array (4, 4, 3):\n{reshaped_array}")

elif choice == 'c':
    reshaped_array = original_array.reshape(2, 2, 2, 6)
    
    print(f"\nReshaped Array (2, 2, 2, 6):\n{reshaped_array}")

else:
    print("Invalid choice. Please enter a, b, or c.")


#### 30.Create a complete reshape validator:

#### - Take array size from the user.

#### - Create array using np.arange().

#### - Take any number of dimensions from the user.

#### - Check if multiplication of dimensions equals total elements.

#### - If valid, reshape and print shape and ndim.

#### - Otherwise display a meaningful error message.


In [1]:
# 30.Create a complete reshape validator:
# - Take array size from the user.
# - Create array using np.arange().
# - Take any number of dimensions from the user.
# - Check if multiplication of dimensions equals total elements.
# - If valid, reshape and print shape and ndim.
# - Otherwise display a meaningful error message.

import numpy as np

array_size = int(input("Enter the size of the array : "))
original_array = np.arange(1, array_size + 1)

try:
    num_dimensions = int(input("Enter the number of dimensions for reshape : "))
    dimensions = []

    for i in range(num_dimensions):
        dim = int(input(f"Enter size for dimension {i + 1} : "))
        dimensions.append(dim)

    if np.prod(dimensions) == array_size:
        reshaped_array = original_array.reshape(dimensions)

        print(f"\nReshaped Array with dimensions {tuple(dimensions)}:\n{reshaped_array}")
        print(f"Shape: {reshaped_array.shape}")
        print(f"Number of dimensions (ndim): {reshaped_array.ndim}")

    else:
        print(f"\nError: The product of the specified dimensions {dimensions} does not equal the total number of elements ({array_size}). Please check your input.")

except ValueError:
    print("Invalid input. Please enter valid integers for array size and dimensions.")


Error: The product of the specified dimensions [5, 5, 1, 2, 1] does not equal the total number of elements (5). Please check your input.
