In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5]])
print(a)
print(a.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
a.ndim

2

In [ ]:
b = np.array([[1,2, 3], [3,4, 5]])
print(b)
print(b.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


In [ ]:
b.ndim

2

In [ ]:
c = np.array([[[1,2], [3,4]], [[1,2], [3,4]]])
print(c)
print(c.ndim)
print(c.shape)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]
3
(2, 2, 2)


### Array Creation by given range

In [ ]:
arr = np.arange(2, 11, 2)
arr

array([ 2,  4,  6,  8, 10])

In [ ]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# change the shape :

arr2 = np.arange(1, 11)
print(arr2.shape)
arr3 = arr2.reshape(5, 2, 1)
arr3

(10,)


array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]]])

In [ ]:
arr2.reshape(5, 1, 2)

array([[[ 1,  2]],

       [[ 3,  4]],

       [[ 5,  6]],

       [[ 7,  8]],

       [[ 9, 10]]])

In [ ]:
arr4 = np.arange(1, 17)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
print(arr4.reshape(4, 2, 2))
print(arr4.reshape(4, 2, 2).shape)
print(arr4.reshape(4, 2, 2).ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)
3
